//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azurlane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azurlane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aircraft_template.lua.txt.
        /// </summary>
        internal static string Aircraft {
            get {
                return ResourceManager.GetString("Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github.com/k0np4ku.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/k0np4ku/Archive-Azur-Lane-Scripts-Autopatcher/master/v3.x.x/main/autopatcher/status.txt.
        /// </summary>
        internal static string AutopatcherStatus {
            get {
                return ResourceManager.GetString("AutopatcherStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/k0np4ku/Archive-Azur-Lane-Scripts-Autopatcher/master/v3.x.x/main/autopatcher/version.txt.
        /// </summary>
        internal static string AutopatcherVersion {
            get {
                return ResourceManager.GetString("AutopatcherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Common]
        ///Version=v3.0.1
        ///DevelopmentMode=true
        ///
        ///[Path]
        ///Tmp=tmp
        ///Thirdparty=3rdparty
        ///
        ///[Mods]
        ///GodMode=false
        ///WeakEnemy=false
        ///GodMode+Damage=false
        ///GodMode+Cooldown=false
        ///GodMode+WeakEnemy=false
        ///GodMode+Damage+Cooldown=false
        ///GodMode+Damage+WeakEnemy=true
        ///GodMode+Damage+Cooldown+WeakEnemy=false
        ///
        ///[Aircraft]
        ///Hp=ignore
        ///HpGrowth=ignore
        ///Accuracy=0
        ///AccuracyGrowth=0
        ///AttackPower=0
        ///AttackPowerGrowth=0
        ///CrashDamage=0
        ///Speed=ignore
        ///
        ///[Weapon]
        ///Damage=300
        ///ReloadMax=120
        ///
        ///[Enemy]
        ///AntiAir=ignore
        ///AntiA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enemy_data_statistics.lua.txt.
        /// </summary>
        internal static string Enemy {
            get {
                return ResourceManager.GetString("Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enemy_data_skill.lua.txt.
        /// </summary>
        internal static string EnemySkill {
            get {
                return ResourceManager.GetString("EnemySkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found: LuaJIT Raw-Bytecode Decompiler (ljd).
        /// </summary>
        internal static string LjdNotFoundMessage {
            get {
                return ResourceManager.GetString("LjdNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found: LuaJIT Just-In-Time Compiler.
        /// </summary>
        internal static string LuajitNotFoundMessage {
            get {
                return ResourceManager.GetString("LuajitNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github.com/k0np4ku/Azur-Lane-Autopatcher.
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship_data_statistics.lua.txt.
        /// </summary>
        internal static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship_skin_template.lua.txt.
        /// </summary>
        internal static string ShipSkin {
            get {
                return ResourceManager.GetString("ShipSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the latest version of Python to solve this issue.
        /// </summary>
        internal static string SolutionPythonMessage {
            get {
                return ResourceManager.GetString("SolutionPythonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer to one of k0np4ku&apos;s repository to solve this issue.
        /// </summary>
        internal static string SolutionReferMessage {
            get {
                return ResourceManager.GetString("SolutionReferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found: UnityEx.exe.
        /// </summary>
        internal static string UnityExNotFoundMessage {
            get {
                return ResourceManager.GetString("UnityExNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weapon_property.lua.txt.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
    }
}
